#!/bin/bash

set -o pipefail
set -e

# Global settings
SCRIPT=$(readlink -f "${0}")
DIR=$(dirname "${SCRIPT}")
cd "${DIR}" || exit 1

python3 -m venv env
. ./env/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r ./requirements.txt

exec bdast -v ./entrypoint.yaml "$@"

exit 1

