vars:
  replace_value: 7890
  other_replacement: "BOOT"

pipeline:
  - type: stdin_yaml
    apply_tags:
      - yaml
      - stdin
  - type: import
    files:
      - "example/files/**/*.yaml"
    recursive: true
    apply_tags:
      - yaml
      - import
  - type: replace
    replace:
      - key: REPLACE_VALUE_HERE
        value: $replace_value
      - key: "Y..."
        value: $other_replacement
        regex: true
  - type: stdout
    prefix: "******** BEGIN ********"
    suffix: "********  END  ********"
